# Generated by Django 2.2.13 on 2020-08-14 21:43

from random import sample, randint

from django.db import migrations


LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'


def forwards_func(apps, schema_editor):
    OrderHeader = apps.get_model('mainapp', 'OrderHeader')
    OrderItem = apps.get_model('mainapp', 'OrderItem')
    OrderHeader.objects.bulk_create([
        OrderHeader(
            reg_id='{1}{0:0>6}{2}{3}{4}'.format(
                randint(1, 999999),
                *sample(LETTERS, 4)
            )
        ) for _ in range(10)
    ])
    for order_h in OrderHeader.objects.all():
        OrderItem.objects.bulk_create([
            OrderItem(
                order=order_h,
                vendor_code='{1}{2}{0:0>5}{3}'.format(
                    randint(1, 99999),
                    *sample(LETTERS, 3)
                ),
                price=randint(2000, 10 ** 6) / 100,
                amount=randint(100, 30000) / 100
            )
            for _ in range(randint(4, 12))
        ])


def reverse_func(apps, schema_editor):
    OrderHeader = apps.get_model('mainapp', 'OrderHeader')
    OrderItem = apps.get_model('mainapp', 'OrderItem')
    OrderItem.objects.all().delete()
    OrderHeader.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
